name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # run manually
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14

    - name: Install
      run: make install

    - name: Test
      run: make test

    - name: Lint
      run: make lint

    - name: Format
      run: make format
